name: First Workflow

on:
    workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: EchoJob1
              run: echo "This is Job 1"

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: EchoJob2
              run: echo "This is Job 2"